server:
  port: 8082

eureka:
  client:
    fetch-registry: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
  batch:
    job:
      enabled: false

  data:
    mongodb:
      #port: 0
      database: fitstore
      #uri: mongodb://localhost:27017/db
      uri: mongodb://mongodb:27017/db
