server:
  port: 8086

eureka:
  client:
    fetch-registry: true

spring:
  data:
    mongodb:
      #port: 0
      database: fitstore
      #uri: mongodb://localhost:27017/db
      uri: mongodb://mongodb:27017/db
